# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: Ubuntu_16_04_x64
  timeoutInMinutes: 90
  pool:
    vmImage: ubuntu-16.04
  variables:
    compiler: gxx_linux-64=7.2.0
    boost_version: 1.67.0
    number_of_cores: nproc
    python_name: python37
  steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH
    - bash: conda env create --quiet --force --file py37_rdkit_beta.yml
      displayName: Create conda environment
    - bash: |
        source activate py37_rdkit_beta
        pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
      displayName: Test with pytest
