# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: Ubuntu_16_04_x64
  timeoutInMinutes: 90
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH
    - bash: conda env create --quiet --force --file env.yml
      displayName: Create conda environment
    - bash: |
        source activate py37_rdkit_beta
        echo $PYTHONPATH
        export PYTHONPATH="$PWD"
        echo $PYTHONPATH
        pytest
      displayName: Test with pytest
- job: macOS X Mojave 10.14
  timeoutInMinutes: 90
  pool:
    vmImage: macOS-10.14
  steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH
    - bash: conda env create --quiet --force --file env.yml
      displayName: Create conda environment
    - bash: |
        source activate py37_rdkit_beta
        echo $PYTHONPATH
        export PYTHONPATH="$PWD"
        echo $PYTHONPATH
        pytest
      displayName: Test with pytest

